---
- name: "Install Docker"
  notify: "Enable and start Docker"
  block:
  - name: "Add Docker GPG apt Key"
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"

  - name: "Add Docker Repository"
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release | lower }} stable"

  - name: "Update apt and install docker-ce"
    ansible.builtin.apt:
      update_cache: true
      name:
        - "docker-ce"

- name: "Install Docker-Compose"
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ install_docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 'a+x'

- name: "Add custom / insecure registries"
  when: install_docker_insecure_registries | default(false)
  notify: "Restart Docker"
  block:
      - name: "Check if /etc/docker exist"
        register: install_docker_folder
        ansible.builtin.stat:
          path: "/etc/docker"

      - name: "Create /etc/docker directory"
        when: not install_docker_folder.stat.exists
        ansible.builtin.file:
          path: "/etc/docker"
          state: directory
          mode: "0600"

      - name: "Import custom dameon.json conf"
        ansible.builtin.template:
          src: "templates/daemon.json.j2"
          dest: "/etc/docker/daemon.json"
          mode: "0600"

- name: "Install Portainer (no SSL)"
  when: (install_docker_portainer | default(false)) and not (install_docker_portainer_ssl | default(false))
  community.docker.docker_container:
    name: "{{ install_docker_portainer_container_name }}"
    image: "portainer/portainer-ce"
    state: "present"
    recreate: false
    exposed_ports:
      - "{{ install_docker_portainer_agent_port }}:9443"
      - "{{ install_docker_portainer_http_port }}:9443"
      - "{{ install_docker_portainer_https_port }}:9443"
    volumes:
      - "{{ install_docker_portainer_volume_name }}:/data"
    devices:
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: "Install Portainer (SSL)"
  when: (install_docker_portainer | default(false)) and (install_docker_portainer_ssl | default(false))
  community.docker.docker_container:
    name: "{{ install_docker_portainer_container_name }}"
    image: "portainer/portainer-ce"
    state: "present"
    recreate: false
    exposed_ports:
      - "{{ install_docker_portainer_agent_port }}:9443"
      - "{{ install_docker_portainer_http_port }}:9443"
      - "{{ install_docker_portainer_https_port }}:9443"
    volumes:
      - "{{ install_docker_portainer_volume_name }}:/data"
    devices:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ inv_install_docker_portainer_ssl_path }}:/certs"
    env:
      sslcert: "{{ install_docker_portainer_ssl_cert }}"
      sslkey: "{{ install_docker_portainer_ssl_key }}"

- name: "Install Watchtower"
  when: install_docker_watchtower | default(false)
  community.docker.docker_container:
    name: "{{ install_docker_watchtower_container_name }}"
    image: "containrrr/watchtower"
    state: "present"
    recreate: false
    devices:
      - "/var/run/docker.sock:/var/run/docker.sock"
