---
- name: "Add custom / insecure registries"
  when: install_docker__insecure_registries | default(false)
  notify: "Restart Docker"
  block:
      - name: "Check if /etc/docker exist"
        register: install_docker__folder
        ansible.builtin.stat:
          path: "/etc/docker"

      - name: "Create /etc/docker directory"
        when: not install_docker__folder.stat.exists
        ansible.builtin.file:
          path: "/etc/docker"
          state: directory
          mode: "0600"

      - name: "Hanble custom lib path for Docker"
        when: install_docker__custom_lib_path is defined
        block:
          - name: "Check if {{ install_docker__custom_lib_path }} exist"
            register: install_docker__folder
            ansible.builtin.stat:
              path: "{{ install_docker__custom_lib_path }}"

          - name: "Create {{ install_docker__custom_lib_path }} directory"
            when: not install_docker__folder.stat.exists
            ansible.builtin.file:
              path: "{{ install_docker__custom_lib_path }}"
              state: directory
              mode: "0600"
              group: "root"
              owner: "root"

      - name: "Import custom dameon.json conf"
        ansible.builtin.template:
          src: "templates/daemon.json.j2"
          dest: "/etc/docker/daemon.json"
          mode: "0600"
          group: "root"
          owner: "root"

- name: "Install Docker"
  notify: "Enable and start Docker"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  block:
  - name: "Add Docker GPG apt Key"
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

  - name: "Add Docker Repository"
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"

  - name: "Update apt and install docker-ce"
    ansible.builtin.apt:
      update_cache: true
      name:
        - "docker-ce"

- name: "Install Docker-Compose"
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ install_docker__compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 'a+x'

- name: "Flush handlers, and start Docker"
  ansible.builtin.meta: flush_handlers

- name: "Install Portainer (no SSL)"
  when: (install_docker__portainer | default(false)) and not (install_docker__portainer_ssl | default(false))
  community.docker.docker_container:
    name: "{{ install_docker__portainer_container_name }}"
    image: "portainer/portainer-ce"
    state: "started"
    recreate: false
    restart_policy: "always"
    ports:
      - "{{ install_docker__portainer_address }}:{{ install_docker__portainer_http_port }}:9000"
      - "{{ install_docker__portainer_address }}:{{ install_docker__portainer_https_port }}:9443"
      - "0.0.0.0:8000:8000"
    volumes:
      - "{{ install_docker__portainer_volume_name }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: "Install Portainer (SSL)"
  when: (install_docker__portainer | default(false)) and (install_docker__portainer_ssl | default(false))
  community.docker.docker_container:
    name: "{{ install_docker__portainer_container_name }}"
    image: "portainer/portainer-ce"
    state: "started"
    recreate: false
    restart_policy: "always"
    ports:
      - "{{ install_docker__portainer_address }}:{{ install_docker__portainer_http_port }}:9000"
      - "{{ install_docker__portainer_address }}:{{ install_docker__portainer_https_port }}:9443"
      - "0.0.0.0:8000:8000"
    volumes:
      - "{{ install_docker__portainer_volume_name }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ install_docker__portainer_ssl_path }}:/certs"
    env:
      sslcert: "{{ install_docker__portainer_ssl_cert }}"
      sslkey: "{{ install_docker__portainer_ssl_key }}"

- name: "Install Watchtower"
  when: install_docker__watchtower | default(false)
  community.docker.docker_container:
    name: "{{ install_docker__watchtower_container_name }}"
    image: "containrrr/watchtower"
    state: "started"
    recreate: false
    restart_policy: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      WATCHTOWER_POLL_INTERVAL: "{{ install_docker__watchtower_poll_interval }}"
      WATCHTOWER_CLEANUP: "{{ install_docker__watchtower_cleanup | lower }}"
      WATCHTOWER_INCLUDE_RESTARTING: "{{ install_docker__watchtower_include_restarting | lower }}"
      WATCHTOWER_INCLUDE_STOPPED: "{{ install_docker__watchtower_include_stopped | lower }}"
      WATCHTOWER_NO_RESTART: "{{ install_docker__watchtower_no_restart | lower }}"

- name: "Handler Docker clean"
  when: install_docker__handle_clean | default(false) and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
  block:
    - name: "Set facts for cleaning job"
      ansible.builtin.set_fact:
        var_handle_docker_clean_cron_file: "{{ handle_docker_clean_cron_file | default('ansible_docker_system_prune') }}"
        var_handle_docker_clean_weekday: "{{ handle_docker_clean_weekday | default('*') }}"
        var_handle_docker_clean_minute: "{{ handle_docker_clean_minute | default('0') }}"
        var_handle_docker_clean_hour: "{{ handle_docker_clean_hour | default('*/6') }}"

    - name: "Create a cron file under /etc/cron.d"
      ansible.builtin.cron:
        cron_file: "{{ var_handle_docker_clean_cron_file }}"
        name: "Docker System Prune"
        weekday: "{{ var_handle_docker_clean_weekday }}"
        minute: "{{ var_handle_docker_clean_minute }}"
        hour: "{{ var_handle_docker_clean_hour }}"
        user: "root"
        job: "docker system prune --all --force && docker volume prune --all --force > /dev/null 2>&1"
        state: present

- name: "Handler Docker No clean"
  when: not (install_docker__handle_clean | default(false) and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"))
  block:
    - name: "Set facts for cleaning job"
      ansible.builtin.set_fact:
        var_handle_docker_clean_cron_file: "{{ handle_docker_clean_cron_file | default('ansible_docker_system_prune') }}"

    - name: "Remove a cron file under /etc/cron.d"
      ansible.builtin.cron:
        cron_file: "{{ var_handle_docker_clean_cron_file }}"
        name: "Docker System Prune"
        state: absent

- name: "Disable SWAP and add cron"
  when: install_docker__disable_swap | default(true) and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
  block:
    - name: "Disable SWAP"
      register: ouput
      changed_when: ouput.rc != 0
      ignore_errors: true
      ansible.builtin.command: "swapoff -a"

    - name: "Create cron task for SWAP disabling"
      ansible.builtin.cron:
        name: "Disable SWAP at boot"
        special_time: "reboot"
        user: "root"
        job: "swapoff -a"
        cron_file: "ansible_disable_swap_after_boot"

- name: "Enable SWAP and remove cron"
  when: not (install_docker__disable_swap | default(true) and (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"))
  block:
    - name: "Enable SWAP"
      register: ouput
      changed_when: ouput.rc != 0
      ansible.builtin.command: "swapon -a"

    - name: "Remove cron task for SWAP disabling"
      ansible.builtin.cron:
        cron_file: "ansible_disable_swap_after_boot"
        name: "Disable SWAP at boot"
        state: absent
