---
- name: "Enable and start Docker"
  register: install_docker__service_status
  failed_when: install_docker__service_status.state != "started"
  changed_when: install_docker__service_status.state != "started"
  ansible.builtin.service:
    name: "docker"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart Docker"
  register: install_docker__service_status
  failed_when: install_docker__service_status.state != "restarted"
  changed_when: install_docker__service_status.state != "restarted"
  ansible.builtin.service:
    name: "docker"
    state: "restarted"
    daemon_reload: true
