---
- name: "Enable and start Docker"
  register: install_docker__service_status
  failed_when: not install_docker__service_status.msg
  changed_when: not install_docker__service_status.msg
  ansible.builtin.service:
    name: "docker"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart Docker"
  register: install_docker__service_status
  failed_when: not install_docker__service_status.msg
  changed_when: not install_docker__service_status.msg
  ansible.builtin.service:
    name: "docker"
    state: "restarted"
    daemon_reload: true
