---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_docker"
      tags:
        - "labocbz.install_docker"
      vars:
        install_docker_portainer: "{{ inv_install_docker_portainer }}"
        install_docker_portainer_http_port: "{{ inv_install_docker_portainer_http_port }}"
        install_docker_portainer_https_port: "{{ inv_install_docker_portainer_https_port }}"
        install_docker_portainer_agent_port: "{{ inv_install_docker_portainer_agent_port }}"
        install_docker_portainer_container_name: "{{ inv_install_docker_portainer_container_name }}"
        install_docker_portainer_volume_name: "{{ inv_install_docker_portainer_volume_name }}"
        install_docker_portainer_ssl: "{{ inv_install_docker_portainer_ssl }}"
        install_docker_portainer_ssl_volume_name: "{{ inv_install_docker_portainer_ssl_volume_name }}"
        install_docker_portainer_ssl_key: "{{ inv_install_docker_portainer_ssl_cert }}"
        install_docker_watchtower: "{{ inv_install_docker_watchtower }}"
        install_docker_watchtower_poll_interval: "{{ inv_install_docker_watchtower_poll_interval }}"
        install_docker_watchtower_cleanup: "{{ inv_install_docker_watchtower_cleanup }}"
        install_docker_watchtower_include_restarting: "{{ inv_install_docker_watchtower_include_restarting }}"
        install_docker_watchtower_include_stopped: "{{ inv_install_docker_watchtower_include_stopped }}"
        install_docker_watchtower_no_restart: "{{ inv_install_docker_watchtower_no_restart }}"
        install_docker_portainer_address: "{{ inv_install_docker_portainer_address }}"
        install_docker_handle_clean: "{{ inv_install_docker_handle_clean }}"
        install_docker_clean_cron_file: "{{ inv_install_docker_clean_cron_file }}"
        install_docker_clean_weekday: "{{ inv_install_docker_clean_weekday }}"
        install_docker_clean_minute: "{{ inv_install_docker_clean_minute }}"
        install_docker_clean_hour: "{{ inv_install_docker_clean_hour }}"
      ansible.builtin.include_role:
        name: "labocbz.install_docker"
