---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "all"
  gather_facts: false
  tasks:

    - name: "Get Docker service current state"
      register: install_docker_service_status
      failed_when: not (install_docker_service_status.status.ActiveState == 'active' or
        install_docker_service_status.status.ActiveState == 'activating' or
        install_docker_service_status.status.ActiveState == 'inactive')
      ansible.builtin.systemd:
        name: "docker"

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker-compose -v"

    - name: "Check Docker insecure registries"
      when: inv_install_docker_insecure_registries is defined
      block:
        - name: "Check Docker registries file"
          register: file_check
          failed_when: not file_check.stat.exists
          ansible.builtin.stat:
            path: "/etc/docker/daemon.json"

        - name: "Check if insecure registries are in the /etc/docker/daemon.json file"
          loop: "{{ inv_install_docker_insecure_registries }}"
          loop_control:
            loop_var: registry
          register: registry_state
          failed_when: registry_state.rc != 0
          changed_when: registry_state.rc != 0
          ansible.builtin.command: "grep -q {{ registry }} /etc/docker/daemon.json"
