---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-docker-dind"
  gather_facts: false
  tasks:

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker -v"

    - name: "Check docker-compose command response"
      register: output
      changed_when: output.rc != 0
      failed_when: output.rc != 0
      ansible.builtin.command: "docker-compose -v"

    - name: "Check Docker insecure registries"
      when: inv_install_docker__insecure_registries is defined
      block:
        - name: "Check Docker registries file"
          register: file_check
          failed_when: not file_check.stat.exists
          ansible.builtin.stat:
            path: "/etc/docker/daemon.json"

        - name: "Check if insecure registries are in the /etc/docker/daemon.json file"
          loop: "{{ inv_install_docker__insecure_registries }}"
          loop_control:
            loop_var: registry
          register: registry_state
          failed_when: registry_state.rc != 0
          changed_when: registry_state.rc != 0
          ansible.builtin.command: "grep -q {{ registry }} /etc/docker/daemon.json"

    - name: "Check Portainer HTTP URL"
      when: (inv_install_docker__portainer | default(false))
      register: result
      failed_when: result.status != 200
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ inv_install_docker__portainer_http_port }}/"
        method: "GET"

    - name: "Check Portainer HTTPS URL"
      when: (inv_install_docker__portainer | default(false)) and (inv_install_docker__portainer_ssl | default(false))
      register: result
      failed_when: result.status != 200
      ansible.builtin.uri:
        url: "https://127.0.0.1:{{ inv_install_docker__portainer_https_port }}/"
        method: "GET"
